Implement in

diff --git a/bin/in b/bin/in
--- a/bin/in
+++ b/bin/in
@@ -1,3 +1,35 @@
 #!/bin/sh
 
-exit 0
+set -e
+
+exec 3>&1 # make stdout available as fd 3 for the result
+exec 1>&2 # redirect all output to stderr for logging
+
+PAYLOAD=$(mktemp $TMPDIR/postgres-resource-request.XXXXXX)
+cat > $PAYLOAD <&0
+
+DEST=$1
+
+URI=$(jq -r '.source.uri // ""' < $PAYLOAD)
+VERSION=$(jq -r '.version.ref // ""' < $PAYLOAD)
+
+echo 'Checking that table exists... '
+EXISTS=$(psql $URI <<EOF
+SELECT EXISTS (
+   SELECT 1
+   FROM   information_schema.tables
+   WHERE  table_schema = 'public'
+   AND    table_name = '$VERSION'
+)
+;
+EOF
+)
+
+if [ "$EXISTS" -eq "0" ]; then
+   echo "ERROR: Table $VERSION does not exist"
+   exit 1
+fi
+echo 'OK'
+
+cat $PAYLOAD > $DEST/version.json
+cat $PAYLOAD >&3
